DEXTERITY_VEST = "+5 Dexterity Vest"
AGED_BRIE = "Aged Brie"
ELIXIR = "Elixir of the Mongoose"
SULFURAS = "Sulfuras, Hand of Ragnaros"
BACKSTAGE_PASSES = "Backstage passes to a TAFKAL80ETC concert"
MANA_CAKE = "Conjured Mana Cake"

APPRECIABLE_ITEMS = [AGED_BRIE, BACKSTAGE_PASSES]
LEGENDARY_ITEMS = [SULFURAS]


HIGH_INFLATION_THRESHOLD = 10
EXTREME_INFLATION_THRESHOLD = 5

MAXIMUM_QUALITY = 50
MINIMUM_QUALITY = 0

EXPIRY_THRESHOLD = 0

DEFAULT_APPRECIATION = 1
DEFAULT_DEPRECIATION = -1
